// GENERATED by karaoke/scripts/build_lyrics.mjs — do not hand-edit.
// Source: reconciled per-word timings from the `karaoke` skill (build_ass.py --json-out).
// Regenerate after re-timing; see scripts/build_lyrics.mjs for the command.
//
// Format: each line is { words: [ { t, w } ] }, t = word start in seconds. The HUD
// shows the last line whose first word's t <= currentTime, sweeping words to the
// accent color as their t passes.

export const LYRICS = [
  { words: [ { t: 29.77, w: "Woke" }, { t: 30.09, w: "up" }, { t: 30.19, w: "to" }, { t: 30.33, w: "static" }, { t: 30.77, w: "and" }, { t: 31.05, w: "a" }, { t: 31.11, w: "burnt-out" }, { t: 31.91, w: "glow" } ] },
  { words: [ { t: 32.93, w: "Running" }, { t: 33.27, w: "through" }, { t: 33.61, w: "echoes" }, { t: 33.99, w: "of" }, { t: 34.07, w: "a" }, { t: 34.27, w: "past" }, { t: 34.83, w: "I" }, { t: 35.07, w: "know" } ] },
  { words: [ { t: 35.49, w: "The" }, { t: 35.65, w: "world" }, { t: 36.25, w: "was" }, { t: 36.53, w: "a" }, { t: 36.63, w: "blur," }, { t: 37.01, w: "summers" }, { t: 37.33, w: "endless" }, { t: 37.64, w: "and" }, { t: 38.27, w: "strange" } ] },
  { words: [ { t: 38.87, w: "Laughed" }, { t: 39.41, w: "in" }, { t: 39.55, w: "the" }, { t: 39.71, w: "chaos," }, { t: 40.19, w: "never" }, { t: 40.53, w: "thought" }, { t: 40.93, w: "we'd" }, { t: 41.31, w: "change" } ] },
  { words: [ { t: 41.97, w: "Salad" }, { t: 43.25, w: "days," }, { t: 44.33, w: "slipping" }, { t: 44.77, w: "through" }, { t: 45.17, w: "cracks" } ] },
  { words: [ { t: 47.52, w: "Rolling" }, { t: 47.96, w: "down" }, { t: 48.38, w: "hills," }, { t: 50.48, w: "never" }, { t: 51.06, w: "looking" }, { t: 51.46, w: "back" } ] },
  { words: [ { t: 54.18, w: "Now" }, { t: 54.36, w: "the" }, { t: 54.58, w: "neon" }, { t: 55.16, w: "hum" }, { t: 56.48, w: "fills" }, { t: 57.06, w: "up" }, { t: 57.32, w: "my" }, { t: 57.98, w: "nights" } ] },
  { words: [ { t: 60.17, w: "Still" }, { t: 60.35, w: "chasing" }, { t: 60.82, w: "shadows" }, { t: 62.06, w: "of" }, { t: 62.2, w: "the" }, { t: 62.38, w: "fading" }, { t: 63.53, w: "lights" } ] },
  { words: [ { t: 76.57, w: "Dreams" }, { t: 76.86, w: "in" }, { t: 76.97, w: "the" }, { t: 77.11, w: "static," }, { t: 77.51, w: "half-remembered" }, { t: 78.69, w: "tunes" } ] },
  { words: [ { t: 79.67, w: "We" }, { t: 79.81, w: "sang" }, { t: 79.98, w: "them" }, { t: 80.15, w: "loud" }, { t: 80.49, w: "beneath" }, { t: 80.95, w: "electric" }, { t: 81.85, w: "moons" } ] },
  { words: [ { t: 82.29, w: "The" }, { t: 82.39, w: "tape" }, { t: 82.99, w: "kept" }, { t: 83.45, w: "warping," }, { t: 83.81, w: "but" }, { t: 84.03, w: "we" }, { t: 84.23, w: "let" }, { t: 84.41, w: "it" }, { t: 84.77, w: "play" } ] },
  { words: [ { t: 85.55, w: "Our" }, { t: 85.73, w: "voices" }, { t: 86.45, w: "cracked," }, { t: 86.89, w: "then" }, { t: 87.27, w: "drifted" }, { t: 87.99, w: "away" } ] },
  { words: [ { t: 88.35, w: "Reflections" }, { t: 89.57, w: "dance" }, { t: 90.17, w: "on" }, { t: 90.39, w: "broken" }, { t: 91.17, w: "glass" } ] },
  { words: [ { t: 91.82, w: "Dreams" }, { t: 92.38, w: "get" }, { t: 92.72, w: "tangled," }, { t: 93.52, w: "time" }, { t: 93.94, w: "moves" }, { t: 94.26, w: "fast" } ] },
  { words: [ { t: 94.68, w: "We" }, { t: 94.84, w: "danced" }, { t: 95.48, w: "with" }, { t: 95.84, w: "ghosts," }, { t: 96.14, w: "felt" }, { t: 96.54, w: "it" }, { t: 96.76, w: "all" }, { t: 97, w: "unwind" } ] },
  { words: [ { t: 98.2, w: "Now" }, { t: 98.52, w: "it's" }, { t: 98.8, w: "all" }, { t: 98.92, w: "screens," }, { t: 99.36, w: "and" }, { t: 99.52, w: "we're" }, { t: 99.74, w: "losing" }, { t: 100.38, w: "our" }, { t: 100.52, w: "minds" } ] },
  { words: [ { t: 101.3, w: "Salad" }, { t: 102.46, w: "days," }, { t: 103.6, w: "slipping" }, { t: 104.02, w: "through" }, { t: 104.4, w: "cracks" } ] },
  { words: [ { t: 106.73, w: "Rolling" }, { t: 107.17, w: "down" }, { t: 107.57, w: "hills," }, { t: 109.69, w: "never" }, { t: 110.29, w: "looking" }, { t: 110.67, w: "back" } ] },
  { words: [ { t: 113.43, w: "Every" }, { t: 113.75, w: "memory" }, { t: 114.93, w: "bends" }, { t: 115.88, w: "until" }, { t: 116.82, w: "it" }, { t: 117.18, w: "breaks" } ] },
  { words: [ { t: 119.34, w: "Still" }, { t: 119.52, w: "chasing" }, { t: 119.98, w: "ghosts" }, { t: 121.22, w: "in" }, { t: 121.36, w: "the" }, { t: 121.58, w: "neon" }, { t: 122.68, w: "wake" } ] },
  { words: [ { t: 135.35, w: "Tomorrows" }, { t: 136.23, w: "blur" }, { t: 136.5, w: "and" }, { t: 137.03, w: "yesterdays" }, { t: 138.03, w: "fade" } ] },
  { words: [ { t: 138.67, w: "Hold" }, { t: 142.43, w: "on" }, { t: 142.65, w: "tight" }, { t: 143.05, w: "to" }, { t: 143.27, w: "whatever" }, { t: 144.05, w: "remains" } ] },
  { words: [ { t: 147.91, w: "The" }, { t: 148.11, w: "past" }, { t: 148.51, w: "and" }, { t: 148.67, w: "the" }, { t: 148.85, w: "present" }, { t: 149.47, w: "blur" }, { t: 150.03, w: "at" }, { t: 150.13, w: "the" }, { t: 150.57, w: "seams" } ] },
  { words: [ { t: 153.54, w: "We're" }, { t: 153.92, w: "always" }, { t: 154.36, w: "longing" }, { t: 155.44, w: "for" }, { t: 155.76, w: "the" }, { t: 155.98, w: "days" }, { t: 157.14, w: "in" }, { t: 157.32, w: "between" } ] },
  { words: [ { t: 158.04, w: "Salad" }, { t: 161.72, w: "days," }, { t: 162.82, w: "wilted" }, { t: 163.5, w: "and" }, { t: 163.72, w: "torn" } ] },
  { words: [ { t: 165.99, w: "Dancing" }, { t: 166.39, w: "through" }, { t: 166.85, w: "nights" }, { t: 168.86, w: "that" }, { t: 169.14, w: "never" }, { t: 169.52, w: "were" }, { t: 169.94, w: "born" } ] },
  { words: [ { t: 172.66, w: "Now" }, { t: 172.84, w: "the" }, { t: 173.33, w: "neon" }, { t: 173.81, w: "hum" }, { t: 174.3, w: "fills" }, { t: 174.79, w: "up" }, { t: 175.76, w: "my" }, { t: 176.4, w: "nights" } ] },
  { words: [ { t: 178.64, w: "Still" }, { t: 178.86, w: "chasing" }, { t: 179.26, w: "shadows" }, { t: 180.54, w: "of" }, { t: 180.68, w: "the" }, { t: 180.84, w: "fading" }, { t: 181.91, w: "lights" } ] },
  { words: [ { t: 194.74, w: "Spinning" }, { t: 195.32, w: "through" }, { t: 195.64, w: "moments," }, { t: 196.14, w: "they're" }, { t: 196.4, w: "never" }, { t: 196.86, w: "too" }, { t: 198.2, w: "far" } ] },
  { words: [ { t: 200.86, w: "The" }, { t: 201.04, w: "best" }, { t: 201.38, w: "days" }, { t: 201.72, w: "are" }, { t: 202, w: "always" }, { t: 202.64, w: "right" }, { t: 202.98, w: "where" }, { t: 203.28, w: "we" }, { t: 204.06, w: "are" } ] },
];
