#!/usr/bin/env node
// Generate karaoke/lyrics.js from reconciled per-word timings.
//
// Input is the JSON emitted by the OWNER/OPERATORS `karaoke` skill's build_ass.py
// (run with --json-out): it has already aligned WhisperX's word timings onto the
// canonical lyrics, so the words are correct and every one has a start/end. We only
// need {start, text} per word for the HUD's word-by-word sweep.
//
//   shape in:  { "lines": [ { "words": [ { "text", "start", "end" }, ... ] }, ... ] }
//   shape out: export const LYRICS = [ { words: [ { t, w }, ... ] }, ... ]
//
// Usage:
//   node karaoke/scripts/build_lyrics.mjs <timings.json> [out.js]
//   # default out is karaoke/lyrics.js next to this script's parent dir
//
// See the karaoke skill (.claude/skills/karaoke) for how the timings JSON is made:
//   build_ass.py --words <whisperx.json> --lyrics <lyrics.md> --out x.ass --json-out timings.json

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const inPath = process.argv[2];
if (!inPath) {
  console.error('usage: build_lyrics.mjs <timings.json> [out.js]');
  process.exit(2);
}
const outPath = process.argv[3] || resolve(__dirname, '..', 'lyrics.js');

const data = JSON.parse(readFileSync(inPath, 'utf8'));
if (!data || !Array.isArray(data.lines)) {
  console.error(`error: ${inPath} has no "lines" array — is this the build_ass.py --json-out file?`);
  process.exit(1);
}

// Round to 2 decimals (10ms) — plenty for a lyric sweep, and keeps the file readable.
const r2 = (n) => Math.round(n * 100) / 100;

const lines = data.lines
  .map((ln) => (ln.words || []).map((w) => ({ t: r2(w.start), w: w.text })))
  .filter((words) => words.length > 0);

const body = lines
  .map((words) => {
    const ws = words.map((o) => `{ t: ${o.t}, w: ${JSON.stringify(o.w)} }`).join(', ');
    return `  { words: [ ${ws} ] },`;
  })
  .join('\n');

const out = `// GENERATED by karaoke/scripts/build_lyrics.mjs — do not hand-edit.
// Source: reconciled per-word timings from the \`karaoke\` skill (build_ass.py --json-out).
// Regenerate after re-timing; see scripts/build_lyrics.mjs for the command.
//
// Format: each line is { words: [ { t, w } ] }, t = word start in seconds. The HUD
// shows the last line whose first word's t <= currentTime, sweeping words to the
// accent color as their t passes.

export const LYRICS = [
${body}
];
`;

writeFileSync(outPath, out);
const nWords = lines.reduce((s, l) => s + l.length, 0);
console.error(`wrote ${outPath}: ${lines.length} lines, ${nWords} words`);
